### ISSUE TITLE
Open A11y Pilot: Requirment of accessible formats

### ISSUE THREAD

**Issue by nschonni** [mgifford/a11y-contracting#1]
> Unless specified otherwise, all written communications will be in an electronic and accessible format. Acceptible formats include .txt, .odf, .doc and .epub. If properly tagged for accessibility .pdf will be accepted.

- Not just PDF, Microsoft formats may also need to be properly tagged to be accessible, and I assume ODF too. Maybe LAC has a write up on the formats.
- It should probably include DOCX, since that is the open(ish) version of Word document format.
- What about email?
- Probably somewhere in the contacting standards, but font size and type
- Cognitive/reading level of the document may need to be stated

PS: My spellcheck is saying the Canadian spelling is "Acceptable"

**Comment by mgifford** [comment]
- My impression is that by default if you produce a PDF the accessibility will generally be pretty bad. Where as with an app like Word or OO, that the defaults are generally tolerable. I might be wrong on this. I'm fine suggesting text or markdown, but think that's probably too far for most gov folks. 
- I've added that.
- I think email = .txt but maybe not. It doesn't actually need to be an attachment. Arg. Folks may well be confused or use it to eliminate folks who knows.
- if it's anything but PDF the font size & type can be changed reasonably easily I think.  Maybe not. I don't want to insert extra ways folks can be disqualified because they didn't format it in Helvetica. 
- Do you think it is safe to say that all material should aim to be at a grade 12 reading level?
- Got spelling ( I think).
