### ISSUE TITLE
Open A11y Pilot: WCAG 2.1 is still at draft

### ISSUE THREAD

**Issue by nschonni** [mgifford/a11y-contracting#7]
> Where possible also conform to WCAG 2.1 and/or EN 301 549.

As of today WCAG 2.1 remains a working draft and can still change quite a lot before it is finalized https://www.w3.org/TR/2017/WD-WCAG21-20170912/
This shouldn't be used as a target

**Comment by mgifford** [comment]
The language is pretty wish-washy. "Where possible, the project should take into consideration the best practices outlined in these open standards:" so the idea is to consider it. That might be to general though for government to be useful. 

I like reminding folks that WCAG 2.1 is being built for a reason. Partly because of mobile, but also because cognitive / learning disabilities & low vision users didn't make the first cut in 2008.

Think I should still nix it?
